<a href="https://colab.research.google.com/github/Nimira43/Tensorflow/blob/main/01_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf

In [3]:
print(tf.__version__)

2.17.1


In [4]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [7]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# Check the dimension of a vector
vector.ndim

1

In [9]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[12, 8],
                       [8, 12]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  8],
       [ 8, 12]], dtype=int32)>

In [10]:
matrix.ndim

2